### ISSUE TITLE
Masterissue Release 1.6

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-cytoscape.js#264]
# Checklist before releasing a new version of SNIK Graph
## ToDos before a new release on GitHub to test the functionality of the SNIK Graph

- [x]  `npm install` , `npm update` bzw upgrade,  `npm run build`,  `npm run test`
- [x]  make sure that both index-dev.html and index-prod.html work
- [x] match the version number in package.json to the new release
- [x] load the graph (maybe in different browsers)
- [x]  clear the cache and try to load again (press F5)
- [x] test all the filters (by turning them on and off)
- [x] press reset view
- [x] hide inter-ontology relations
- [x]  press recalculate layout
- [x]  show inter-ontology relations again and recalculate
- [x]  test the day mode (options)
- [x] test all links (under Services and Help)
- [x] test the zoom element (panzoom)
- [x] try if the language switches from english to german to farsi and back to english
- [x] search for something
- [x] highlight all entries
- [x] mark one of the entries (in the inner circle) and choose path
- [x] check if the path is displayed and the labels (on nodes and edges) are existing (scroll in)
- [x] reset view
- [x] mark one entry, display starpath, doublestar, circlestar, star in the same way
- [x] reset view
- [x] mark one entry, mark another, display the spiderworm and check for labels and agility
- [x] reset view
- [x] remove at least one node and one edge using the contextmenu and del-button
- [x] check if the description, LodLive and the other entries in the contextmenu are working

**Comment by ThomasPause** [comment]
Release 1.6 Done
